### ISSUE TITLE
Implement test coverage reporting with Bun Test

### ISSUE THREAD

**Issue by sakataka** [sakataka/tetris-game2#40]
## Summary
Add test coverage reporting to improve code quality visibility and support our TDD development approach.

## Background
- Project follows TDD methodology as outlined in CLAUDE.md
- Currently using Bun Test (v1.2.17) with 34 test files
- Coverage reporting is currently disabled in bunfig.toml
- .gitignore already includes coverage directory

### 1. Enable Coverage in bunfig.toml
```toml
[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageSkipTestFiles = true
coverageThreshold = { lines = 0.8, functions = 0.8 }
```

### 2. Add package.json Scripts
```json
"test:coverage": "bun test --coverage",
"test:coverage:ci": "bun test --coverage --coverage-reporter=lcov"
```

### 3. Update CI Workflow
- Generate coverage reports in GitHub Actions
- Optional: Integrate with coverage reporting services

## Benefits
- Aligns with project's TDD philosophy
- Provides visibility into untested code areas
- Helps maintain quality standards
- Simple to implement with existing Bun Test setup

## Implementation Strategy
1. Start with current coverage level as baseline
2. Focus on critical game logic areas (src/game/)
3. Gradually improve coverage over time

Priority: Medium
Effort: Low (2-3 hours)
